### PR TITLE
Highly Swift Support

### PR DESCRIPTION
**Pull request by EZ-NET**
Thank you for creating a great Xcode Plugin.
I added features for using more comfortable in Swift.

* Support nested enum types.
* Support enum types implemented by type extension.
* Support Optional<Wrapped> and ImplicitlyUnwrappedOptional<Wrapped>. There are defined by enum type.
* Support enum type wapped in single element tuple. This is seen in a closure receive only one argument of enum type.
* Ready to enum cases autocompletion immediately. (There is no need to wait for a few minutes or more to receive appropriate `IDEIndexDidChangeNotification` in Swift.)

How about this PR.
Thank you 🙂

### CODE REVIEW

**Comment by EZ-NET** [comment]
I found unnecessary implementation for `IDEIndexClassSymbol` in this PR.
I removed it. (cb86736)

**Comment by stefanceriu** [comment]
Hi Tomohiro, this is massively awesome, thank you !

**Comment by stefanceriu** [comment]
I've taken the liberty to change some things around and make the project more consistent overall, hope you don't mind.
Also, there's a new release here https://github.com/stefanceriu/SCXcodeSwitchExpander/releases/tag/v1.2.0

Cheers,
Stefan

**Comment by EZ-NET** [comment]
I'm very glad.
Thank you so much ! 🙂

**Pull request merged**
